version: '2'
services:
  prometheus:
    image: quay.io/prometheus/prometheus
    volumes:
    - ./storage/prometheus:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus/rules:/etc/prometheus
    command:
    - "-config.file=/etc/prometheus/prometheus.yml"
    - "-storage.local.path=/prometheus"
    - "-web.console.libraries=/etc/prometheus/console_libraries"
    - "-web.console.templates=/etc/prometheus/consoles"
    - "-web.listen-address=:9090"
    - "-alertmanager.url=http://alertmanager:9093"
    networks:
    - back
  alertmanager:
    image: quay.io/prometheus/alertmanager
    volumes:
    - ./alertmanager/:/etc/alertmanager/
    - ./storage/alertmanager/:/alertmanager
    command:
    - '-config.file=/etc/alertmanager/config.yml'
    - '-storage.path=/alertmanager'
    networks:
    - back
  grafana:
    image: grafana/grafana
    volumes:
    - ./storage/grafana:/var/lib/grafana
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD
    - GF_USERS_ALLOW_SIGN_UP=false
    networks:
    - back
  web:
    image: nginx
    volumes:
    - ./htpasswd:/etc/nginx/htpasswd
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
    - VIRTUAL_HOST=grafana.${HOSTNAME},prometheus.${HOSTNAME}
    networks:
    - back
    - lb_web
networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.5.0/28
  lb_web:
    external: true
